# Generated by Django 4.2.7 on 2023-11-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedia',
            old_name='prece_usd',
            new_name='price_usd',
        ),
    ]
