# Generated by Django 4.2.7 on 2023-11-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_prece_usd_expedia_price_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedia',
            old_name='srch_lenggth_of_stay',
            new_name='srch_length_of_stay',
        ),
    ]
