# Generated by Django 4.2.7 on 2023-11-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_srch_lenggth_of_stay_expedia_srch_length_of_stay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedia',
            old_name='comp2_rate_percenter_diff',
            new_name='comp2_rate_percent_diff',
        ),
    ]
