# Generated by Django 4.2.7 on 2023-11-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_comp2_rate_percenter_diff_expedia_comp2_rate_percent_diff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usurio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
