# Generated by Django 4.2.5 on 2023-11-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
