# Generated by Django 4.2.5 on 2023-11-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('contra', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Usurio',
        ),
    ]
