# Generated by Django 4.2.5 on 2023-11-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_usuario_delete_usurio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
