# Generated by Django 4.2.5 on 2023-11-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usurio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
