# Generated by Django 4.2.6 on 2023-11-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_usurio_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expedia',
            table=None,
        ),
    ]
