# Generated by Django 4.2.6 on 2023-11-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_expedia_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
