from django.db import models
# Create your models here.


# Modelo de la tabla usuarios
class Usuario(models.Model):
    nombre = models.CharField(max_length = 10),
    contrasenia = models.CharField(max_length = 8)

# Modelo de la tabla Expedia
class Expedia(models.Model):
    srch_id = models.IntegerField()
    site_id = models.IntegerField()
    visitor_location_country_id = models.IntegerField()
    visitor_hist_starrating = models.FloatField()
    visitor_hist_adr_usd = models.FloatField()
    prop_country_id = models.IntegerField()
    prop_id = models.IntegerField()
    prop_starrating = models.IntegerField()
    prop_review_score = models.FloatField()
    prop_brand_bool = models.IntegerField()
    prop_location_score1 = models.FloatField()
    prop_location_score2 = models.FloatField()
    price_usd = models.FloatField()
    promotion_flag = models.IntegerField()
    srch_destination_id = models.IntegerField()
    srch_length_of_stay = models.IntegerField()
    srch_booking_window = models.IntegerField()
    srch_adults_count = models.IntegerField()
    srch_children_count = models.IntegerField()
    srch_room_count = models.IntegerField()
    srch_saturday_night_bool = models.IntegerField()
    srch_query_affinity_score = models.FloatField()
    orig_destination_distance = models.FloatField()
    comp1_rate = models.FloatField()
    comp1_inv = models.FloatField()
    comp1_rate_percent_diff = models.FloatField()
    comp2_rate = models.FloatField()
    comp2_inv = models.FloatField()
    comp2_rate_percent_diff = models.FloatField()
    comp3_rate = models.FloatField()
    comp3_inv = models.FloatField()
    comp3_rate_percent_diff = models.FloatField()
    comp4_rate = models.FloatField()
    comp4_inv = models.FloatField()
    comp4_rate_percent_diff = models.FloatField()
    comp5_rate = models.FloatField()
    comp5_inv = models.FloatField()
    comp5_rate_percent_diff = models.FloatField()
    comp6_rate = models.FloatField()
    comp6_inv = models.FloatField()
    comp6_rate_percent_diff = models.FloatField()
    comp7_rate = models.FloatField()
    comp7_inv = models.FloatField()
    comp7_rate_percent_diff = models.FloatField()
    comp8_rate = models.FloatField()
    comp8_inv = models.FloatField()
    comp8_rate_percent_diff =models.FloatField()
    day = models.IntegerField()
    month = models.IntegerField()
    year = models.IntegerField()